### ISSUE TITLE
Compile error in ubuntu 14.04

### ISSUE THREAD

**Issue by littleseytan** [cr8tr/omnidome#4]
Hi,
   I am trying to setup omnidome on my ubuntu  14.04 environment. When I run "cmake -DCMAKE_BUILD_TYPE=Release . && make" command I got error below.

> In file included from /home/alisihab/omnidome/src/lib/visual/Box.cpp:20:
/home/alisihab/omnidome/include/omni/visual/Box.h:46:12: warning: private field 'wireframe_' is not
      used [-Wunused-private-field]
      bool wireframe_ = false;
           ^
1 warning generated.
[  1%] Building CXX object CMakeFiles/omni.dir/src/lib/visual/Tuning.cpp.o
[  1%] Building CXX object CMakeFiles/omni.dir/src/lib/visual/WarpGrid.cpp.o
In file included from /home/alisihab/omnidome/src/lib/visual/WarpGrid.cpp:20:
/home/alisihab/omnidome/include/omni/visual/WarpGrid.h:60:12: error: no type named 'unique_ptr' in
      namespace 'std'
      std::unique_ptr<Circle> circle_;
      ~~~~~^
/home/alisihab/omnidome/include/omni/visual/WarpGrid.h:60:22: error: expected member name or ';'
      after declaration specifiers
      std::unique_ptr<Circle> circle_;
      ~~~~~~~~~~~~~~~^
/home/alisihab/omnidome/src/lib/visual/WarpGrid.cpp:91:18: error: use of undeclared identifier
      'circle_'
            if (!circle_) return;
                 ^
/home/alisihab/omnidome/src/lib/visual/WarpGrid.cpp:105:21: error: use of undeclared identifier
      'circle_'
                    circle_->drawLine(_point.pos(),_rX,_rY);
                    ^
/home/alisihab/omnidome/src/lib/visual/WarpGrid.cpp:111:25: error: use of undeclared identifier
      'circle_'
                        circle_->drawFill(_point.pos(),_rX,_rY);
                        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
6 errors generated.
make[2]: *** [CMakeFiles/omni.dir/src/lib/visual/WarpGrid.cpp.o] Error 1
make[1]: *** [CMakeFiles/omni.dir/all] Error 2
make: *** [all] Error 2


Can you help me please?

--littleseytan

**Comment by cr8tr** [comment]
Hey, just push a new version to master, please test if this fixes the error (it compiles on my machine on ubuntu 14.04 now).

**Comment by littleseytan** [comment]
Hi cr8tr,
        Thanks for revision it works now.
